Arm pluging cross-compilation dockerfile for Debian Buster
openvinotoolkit/openvino_contrib pull request #136
Opened 2021-05-15 11:21 UTC by terfendail

2021-05-17 11:15 UTC, alvoron approved these changes

2021-05-17 11:18 UTC, alvoron commented
Do we need to rename `Dockerfile.RPi32` and `Dockerfile.RPi64` to specify Debian release?

2021-05-18 17:25 UTC, terfendail commented
@alvoron Could you please check Readme file update?

2021-05-19 08:40 UTC, alvoron requested changes

2021-05-19 08:40 UTC, alvoron commented on modules/arm_plugin/README.md
> +OpenVINO™ and ARM CPU plugin could be built in Docker* container for [32-bit](Dockerfile.RPi32_stretch or Dockerfile.RPi32_buster) Debian*
MD link to Dockerfile is broken here. 
Probably need to provide links to all Dockerfiles here.

2021-05-21 13:29 UTC, alvoron commented
@terfendail please pull the latest changes from master - it should fix arm build on Azure.

2021-05-24 09:56 UTC, alvoron approved these changes

2021-05-24 09:58 UTC, merged