[ARM Plugin] added adaptive_pooling reference implementation
openvinotoolkit/openvino_contrib pull request #238
Opened 2021-11-16 14:47 UTC by rayonnant14

2021-11-17 11:12 UTC, terfendail requested changes

2021-11-17 11:12 UTC, terfendail commented on modules/arm_plugin/src/arm_converter/arm_converter_adaptive_pooling.cpp
> +        node.input(1), indexTypes);
Shouldn't it be `node.output(1)`?

2021-11-18 19:20 UTC, rayonnant14 commented on modules/arm_plugin/src/arm_converter/arm_converter_adaptive_pooling.cpp
> +        node.input(1), indexTypes);
fixed, thank you!

2021-11-24 07:04 UTC, terfendail approved these changes

2021-11-24 08:22 UTC, merged