Fix quantize model run and tests on Android
openvinotoolkit/openvino_contrib pull request #270
Opened 2021-12-18 17:57 UTC by allnes

2021-12-20 05:19 UTC, ilyachur commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +#define REGISTER_PASS manager.register_pass<ov::pass::GraphRewrite>()->add_matcher
@GlebKazantaev it looks like a WA

2021-12-20 08:43 UTC, apankratovantonp commented
Needed More detailed explanation

2021-12-20 08:54 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +        REGISTER_PASS<pass::ConvertConcat>();
Lines 308 and 309 looks local as well

2021-12-20 09:03 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +    REGISTER_PASS<pass::ReplacePowerByMul>();
Line 159 looks local as well

2021-12-20 11:48 UTC, allnes commented
@apankratovantonp 
Our manual arm quantization transformations couldn't run on arm android platform (for example 
[error.txt](https://github.com/openvinotoolkit/openvino_contrib/files/7744976/error.txt)), this workaround `manager.register_pass<ov::pass::GraphRewrite>()->add_matcher`  fix it. But this fix break inference on RPI with same errors. That why we create macros
```
#if(__ANDROID__)
#define REGISTER_PASS manager.register_pass<ov::pass::GraphRewrite>()->add_matcher
#else
#define REGISTER_PASS manager.register_pass
#endif
```

2021-12-20 12:19 UTC, alvoron commented
@apankratovantonp I assume we don't consider merging this PR. It's being used as an example how we avoid dynamic_pointer_castn issue in ARM plugin to discuss the issue with nGraph guys.

2021-12-23 07:36 UTC, allnes commented
@terfendail @GlebKazantaev please review

2021-12-24 08:42 UTC, terfendail requested changes
Even though the issue is easily reproduceable for quantized nets only the root cause is generic. So I prefer to wrap with `GraphRewrite` all registrations for local `MatcherPass` instead of just that we combine for simultaneous execution.
I don't think the overhead will be high while we ensure all transformations are working as expected

2021-12-24 08:42 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +        manager.register_pass<pass::ReplacePowerByMul>();
`ReplacePowerByMul` is a local `MatcherPass` also

2021-12-24 08:42 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +        manager.register_pass<pass::ConvertGroupConvolution>();
Local `MatcherPass`-es also

2021-12-24 08:42 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +        ov::pass::Manager manager;
Lines 248-251, 261-262,265 and probably some more are local `MatcherPass`-es also

2021-12-24 08:42 UTC, terfendail commented on modules/arm_plugin/src/transformations/arm_optimizations.cpp
> +            ov::pass::Manager manager;
I think it would be better to use single `Manager` for whole arm quantization processing and execute `run_passes` once

2021-12-24 11:51 UTC, apankratovantonp commented
Seems that we do not export RTTI for this classes as we do not export these classes from library too.
We can export our local pass symbols from library: @ilya-lavrenov @ilyachur  could you advise us how we should do it:
- Should we produce our local API macro or we can use `OPENVINO_API` macro. How should we implement it. 
- Or should we use OPENVINO_RTTI macro? 
- @allnes  we should apply the API macro to all passes objects
- @allnes as we dose not override any virtual functions maybe we need to override at least the destructor and place its default implementation into cpp file for each pass.

@ilya-lavrenov @GlebKazantaev we need to add this case into documentation

2021-12-29 19:09 UTC, apankratovantonp approved these changes

2021-12-30 20:23 UTC, allnes commented
@terfendail @apankratovantonp @alvoron please review

2022-01-11 09:22 UTC, terfendail approved these changes

2022-01-11 12:04 UTC, merged