[NVIDIA] Fix convolution fusion
openvinotoolkit/openvino_contrib pull request #523
Opened 2022-12-19 14:50 UTC by nkogteva

- *Fix case when `Add` has `FusedConvolution` on both inputs which lead to hangs in mobilenet\* topologies*
- *Add transformation unit tests*

2022-12-20 14:15 UTC, vladimir-paramuzov requested changes

2022-12-20 14:15 UTC, vladimir-paramuzov commented on modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
> +        if (fused_conv0) {
need to check node ids here as well to ensure that there's no dependency between fused_conv and input1

2022-12-21 07:37 UTC, nkogteva commented on modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
> +    const auto bias_rank = bias_shape.size();
Added

2022-12-21 07:37 UTC, nkogteva commented on modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
> +    return (shape0.to_shape() == shape1.to_shape());
Added check

2022-12-21 07:37 UTC, nkogteva commented on modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
> +    if (bias_shape.at(bias_shape.size() - nchw_channel_dim_reverse_offset) !=
Added check and test

2022-12-21 11:33 UTC, vladimir-paramuzov approved these changes

2022-12-21 11:34 UTC, merged