OpenVINO Code VSCode Extension
openvinotoolkit/openvino_contrib pull request #713
Opened 2023-08-29 13:53 UTC by apaniukov

2023-08-29 20:14 UTC, alvoron requested changes
1. Root repository `README` is not modified - new module should be mentioned there.
2. `LICENSE` file is empty - do we really need dedicated LICENSE file? May we use root LICENSE?
3. Third party dependencies (if any) should be added to `third-party-programs.txt`
4. Any new Azure pipelines to validate the module?

2023-08-30 13:01 UTC, yatarkan commented
> 1. Root repository `README` is not modified - new module should be mentioned there.
> 2. `LICENSE` file is empty - do we really need dedicated LICENSE file? May we use root LICENSE?
> 3. Third party dependencies (if any) should be added to `third-party-programs.txt`
> 4. Any new Azure pipelines to validate the module?

@alvoron Thanks for your review.
1. I  have updated root `README.md` file with short description of new module
2. Empty license file was deleted - let's use root license for now
3. If I understand it correctly, we do not have anything to add to the `third-party-programs.txt`. We do have some dependencies (e.g. npm packages and pip modules installed from package managers), however I assume all of them should not be listed in `third-party-programs.txt` as we do not include them as git submodules or "as-is" source code files and we do not redistribute them. Please correct me if I am missing something here.
4. We don't have automatic validation through CI for now, but we are planning to add it later.

Should we also make changes in `.github/CODEOWNERS` file and add separate maintainers team (e.g. `@openvinotoolkit/openvino_contrib-openvino_code-maintainers`) for newly added module?

2023-08-30 14:52 UTC, yatarkan approved these changes

2023-08-30 18:11 UTC, andrei-kochin approved these changes

2023-09-05 18:12 UTC, ilya-lavrenov approved these changes

2023-09-05 18:14 UTC, merged