[JAVA API][ARM CPU] Add COCO Android ARM demo (update old version)
openvinotoolkit/openvino_contrib pull request #924
Opened 2024-06-10 08:03 UTC by allnes

Update demo for Android ARM devices

2024-06-10 08:06 UTC, ilya-lavrenov approved these changes

2024-06-12 16:59 UTC, likholat requested changes

2024-06-12 16:59 UTC, likholat commented on modules/android_demos/coco_detection_android_demo/app/src/main/java/org/intel/openvino/MainActivity.java
> +            System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
Now we're loading native OV libs in OV Java bindings, so we don't need to do it here:
https://github.com/openvinotoolkit/openvino_contrib/blob/7239f8201bf18d953298966afd9161cff50b2d38/modules/java_api/src/main/java/org/intel/openvino/NativeLibrary.java#L16

2024-06-12 16:59 UTC, likholat commented on modules/android_demos/coco_detection_android_demo/app/src/main/java/org/intel/openvino/MainActivity.java
> +                    "Failed to load native OpenVINO libraries\n" + e.toString());
```suggestion
                    "Failed to load native OpenCV libraries\n" + e.toString());
```

2024-06-13 16:43 UTC, likholat commented on modules/android_demos/coco_detection_android_demo/README.md
> +> To build the project correctly, you should write in OpenCV `build.gradle` file `kotlinOptions` parameter same as current project's `build.gradle` file
Please describe expected demo output. Maybe we can also add a screenshot/gif.

2024-06-13 16:53 UTC, likholat commented on modules/android_demos/coco_detection_android_demo/README.md
> +This is a object detection demo for Android ARM devices.
```suggestion
This demo showcases inference of Object Detection network on Android ARM devices using [OpenVINO Java API](https://github.com/openvinotoolkit/openvino_contrib/tree/7239f8201bf18d953298966afd9161cff50b2d38/modules/java_api).
```

2024-06-13 17:56 UTC, merged