[java_api] [coco_detection_android_demo] Updating build.gradle to build libraries in Linux for android deployment
openvinotoolkit/openvino_contrib pull request #927
Opened 2024-07-25 13:13 UTC by IndraTheZeus

When building the openvino-java-api.jar, if you do not build in android OS you end up building the incorrect libraries leading to errors like java.lang.UnsatisfiedLinkError: No implementation found for long org.intel.openvino.Core.GetCore() (tried Java_org_intel_openvino_Core_GetCore and Java_org_intel_openvino_Core_GetCore__) - is the library loaded, e.g. System.loadLibrary?

In order to solve this, you must change the build.gradle file to the correct variables for the libraries are set and discovered 

This issue was discovered  by @Kabor42 from IRF Solutions KFT. Budapest, Hungary. It fixes #926

2024-07-30 11:11 UTC, likholat commented on modules/java_api/build.gradle
> +def tbb_dir = System.getenv('TBB_DIR') ?: "/openvino-android/one-tbb-install/lib/cmake/TBB"
Shouldn't we define the full path to `openvino-android` repo? Please see: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_android.md#create-a-work-directory

Something like:
```suggestion
def tbb_dir = System.getenv('TBB_DIR') ?: System.getenv('OPV_HOME_DIR') + "/one-tbb-install/lib/cmake/TBB"
```

2024-07-30 11:11 UTC, likholat commented on modules/java_api/build.gradle
> +def openVinoDir = System.getenv('INTEL_OPENVINO_DIR') ?: "/openvino-android/openvino_install"
Same as above for `tbb_dir`

2024-07-31 14:51 UTC, IndraTheZeus commented on modules/android_demos/coco_detection_android_demo/app/src/main/java/org/intel/openvino/MainActivity.java
> +    public static final String MODEL_XML = "ssd_mobilenet_v1_coco.xml";
ssd_mobilenet_v2 doesnt seem to be available on the public repos

2024-08-01 13:22 UTC, allnes requested changes

2024-08-01 13:22 UTC, allnes commented on modules/java_api/build.gradle
> +def tbb_dir = System.getenv('TBB_DIR') ?: System.getenv('OPV_HOME_DIR') + "/one-tbb-install/lib/cmake/TBB"
one-tbb-install directory can be changed, it's just example and there cannot be a universal way to find TBB, that why System.getenv('TBB_DIR') is required

2024-08-01 13:22 UTC, allnes commented on modules/java_api/build.gradle
> +println ">>> INTEL_OPENVINO_DIR -> ${openVinoDir}"
please add logging or remove simple print messages in demos

2024-08-01 13:22 UTC, allnes commented on modules/java_api/build.gradle
> +def openVinoDir = System.getenv('INTEL_OPENVINO_DIR') ?: System.getenv('OPV_HOME_DIR') + "/openvino_install"
same as TBB

2024-08-01 13:22 UTC, allnes commented on modules/java_api/build.gradle
> +            println ">>> Adding ${details.file.name} to native_resources"
sames sa with logging

2026-08-04 02:17 UTC, closed without merging